name: Scala CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache coursier cache
      uses: actions/cache@v1
      with:
        path: ~/.coursier/cache
        key: ${{ runner.os }}-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-coursier-cache-${{ hashFiles('**/*.sbt') }}
          ${{ runner.os }}-coursier-cache

    - name: Cache ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-ivy-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-ivy-cache-${{ hashFiles('**/*.sbt') }}
          ${{ runner.os }}-ivy-cache

    - name: Cache sbt
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          ${{ runner.os }}-sbt

    - name: Test
      run: sbt test

    - name: Package
      run: sbt packageArtifactZip

    - name: IntelliJ Platform Plugin Verifier
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
      with:
        plugin-location: 'target/RubyRefactorings-*.zip'
        ide-versions: |
          ideaIU:LATEST-EAP-SNAPSHOT

    - name: Get commit timestamp
      uses: actions/github-script@0.3.0
      id: commit-timestamp
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const commit_details = await github.git.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha
          });
          return Date.parse(commit_details.data.author.date) / 1000;

    - name: Publish nightly
      if: github.ref == 'refs/head/main'
      run: sbt publishPlugin nightly
      env:
        NIGHTLY_VERSION_SUFFIX: .${{ steps.commit-timestamp.outputs.result }}
