name: Scala CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Get commit timestamp
      uses: actions/github-script@v3
      id: commit-timestamp
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const commit_details = await github.git.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha
          });
          return Date.parse(commit_details.data.author.date) / 1000;

    - name: Cache coursier cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: ${{ runner.os }}-coursier-cache-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-coursier-cache-${{ hashFiles('**/*.sbt') }}
          ${{ runner.os }}-coursier-cache

    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/**/*.scala') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          ${{ runner.os }}-sbt

    - name: Setup tmate session 0
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
      env:
        VERSION_SUFFIX: ${{ steps.commit-timestamp.outputs.result }}

    - name: Package
      run: sbt packageArtifactZip "generateUpdatePluginsXml https://github.com/$GITHUB_REPOSITORY/releases/download/nightly/"
      env:
        VERSION_SUFFIX: ${{ steps.commit-timestamp.outputs.result }}

    - name: Setup tmate session 1
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
      env:
        VERSION_SUFFIX: ${{ steps.commit-timestamp.outputs.result }}
